server:
  port: 8080
spring:
  application:
    name: test
  profiles:
    active: dev
    include: redis,mybatisplus,oss,pay
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: 123456
logging:
  level:
    net.wlfeng.test: DEBUG
pdf:
  ftlPath: templates/user.ftl
#apache httpclient日志级别，默认的debug级别打印了太多无用日志
log4j:
  logger:
    org:
      apache:
        http: info
    httpclient:
      wire: info
test:
  shortMsg:
    sendMock: true
    mockMobile: 12345678910
ali:
  ocr:
    appCode: e*******************7
    appKey: 1*****2
    appSecret: K*************************6